const WHATSAPP='59899000000';
const ADMIN_PASSWORD='123456789Muy';
const defaults=[
 {id:'onix-rs',brand:'Chevrolet',model:'Onix RS',year:2025,price:24500,condition:'0 km',type:'Hatch',km:0,fuel:'Nafta',transmission:'Automática',description:'Diseño deportivo, excelente tecnología y seguridad para disfrutar cada viaje.',images:['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=1200&q=85']},
 {id:'compass',brand:'Jeep',model:'Compass Limited',year:2021,price:32900,condition:'Usado',type:'SUV',km:48500,fuel:'Nafta',transmission:'Automática',description:'SUV confortable y completo, ideal para ciudad y ruta.',images:['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=85']},
 {id:'corolla',brand:'Toyota',model:'Corolla XEI',year:2022,price:29800,condition:'Usado',type:'Sedán',km:36000,fuel:'Híbrido',transmission:'Automática',description:'Confiabilidad, bajo consumo y gran comodidad para todos los días.',images:['https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=85']},
 {id:'nivus',brand:'Volkswagen',model:'Nivus Highline',year:2025,price:36500,condition:'0 km',type:'SUV',km:0,fuel:'Nafta',transmission:'Automática',description:'SUV coupé moderno, conectado y equipado con asistencias de conducción.',images:['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1200&q=85']},
 {id:'208',brand:'Peugeot',model:'208 GT',year:2024,price:29900,condition:'0 km',type:'Hatch',km:0,fuel:'Nafta',transmission:'Automática',description:'Estilo francés, puesto de conducción i-Cockpit y prestaciones deportivas.',images:['https://images.unsplash.com/photo-1597007030739-6d2e7172ee31?auto=format&fit=crop&w=1200&q=85']},
 {id:'cronos',brand:'Fiat',model:'Cronos Precision',year:2023,price:21900,condition:'Usado',type:'Sedán',km:22000,fuel:'Nafta',transmission:'Automática',description:'Gran baúl, confort y economía en un sedán versátil.',images:['https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=85']}
];
let vehicles=JSON.parse(localStorage.getItem('lrvVehicles')||'null')||structuredClone(defaults);
const $=s=>document.querySelector(s); const money=n=>`USD ${Number(n).toLocaleString('es-UY')}`;
function save(){localStorage.setItem('lrvVehicles',JSON.stringify(vehicles));render();renderAdmin()}
function filtered(){let list=[...vehicles],q=$('#search').value.toLowerCase(),c=$('#condition').value,t=$('#type').value,s=$('#sort').value;list=list.filter(v=>(`${v.brand} ${v.model} ${v.year}`.toLowerCase().includes(q))&&(!c||v.condition===c)&&(!t||v.type===t));if(s==='price-desc')list.sort((a,b)=>b.price-a.price);if(s==='price-asc')list.sort((a,b)=>a.price-b.price);if(s==='year-desc')list.sort((a,b)=>b.year-a.year);return list}
function render(){let list=filtered();$('#resultCount').textContent=`${list.length} vehículo${list.length===1?'':'s'}`;$('#vehicleGrid').innerHTML=list.map(v=>`<article class="vehicle-card" data-id="${v.id}"><img src="${v.images[0]}" alt="${v.brand} ${v.model}" loading="lazy"><div class="card-body"><div class="badges"><span class="badge red">${v.condition}</span><span class="badge">${v.type}</span></div><h3>${v.brand} ${v.model}</h3><div class="meta">${v.year} · ${Number(v.km).toLocaleString('es-UY')} km · ${v.transmission}</div><p class="price">${money(v.price)}</p></div></article>`).join('')||'<p>No encontramos vehículos con esos filtros.</p>';document.querySelectorAll('.vehicle-card').forEach(x=>x.onclick=()=>detail(x.dataset.id))}
function detail(id){let v=vehicles.find(x=>x.id===id);if(!v)return;let msg=encodeURIComponent(`Hola, quiero cotizar el ${v.brand} ${v.model} ${v.year}.`);$('#detailContent').innerHTML=`<div class="detail-layout"><div><img class="main-image" id="mainImage" src="${v.images[0]}" alt="${v.brand} ${v.model}"><div class="thumbs">${v.images.map(i=>`<img src="${i}" alt="Vista del vehículo">`).join('')}</div></div><div><div class="badges"><span class="badge red">${v.condition}</span><span class="badge">${v.type}</span></div><h2>${v.brand} ${v.model}</h2><p class="price">${money(v.price)}</p><div class="specs"><div class="spec"><small>Año</small><b>${v.year}</b></div><div class="spec"><small>Kilometraje</small><b>${Number(v.km).toLocaleString('es-UY')} km</b></div><div class="spec"><small>Combustible</small><b>${v.fuel}</b></div><div class="spec"><small>Transmisión</small><b>${v.transmission}</b></div></div><p>${v.description}</p><a class="button whatsapp" target="_blank" rel="noopener" href="https://wa.me/${WHATSAPP}?text=${msg}">Solicitar cotización</a></div></div>`;openModal('detailModal');document.querySelectorAll('.thumbs img').forEach(i=>i.onclick=()=>$('#mainImage').src=i.src)}
function openModal(id){$('#'+id).classList.add('open');$('#'+id).setAttribute('aria-hidden','false')}
function closeModal(id){$('#'+id).classList.remove('open');$('#'+id).setAttribute('aria-hidden','true')}
$('#generalWhatsapp').href=`https://wa.me/${WHATSAPP}?text=${encodeURIComponent('Hola, quiero consultar por los vehículos disponibles.')}`;
['search','condition','type','sort'].forEach(id=>$('#'+id).addEventListener('input',render));
$('#adminOpen').onclick=()=>openModal('loginModal');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
$('#loginForm').onsubmit=e=>{e.preventDefault();if($('#password').value===ADMIN_PASSWORD){closeModal('loginModal');$('#password').value='';$('#loginError').textContent='';renderAdmin();openModal('adminModal')}else $('#loginError').textContent='Contraseña incorrecta.'};
function renderAdmin(){$('#adminList').innerHTML=vehicles.map(v=>`<div class="admin-row"><span><b>${v.brand} ${v.model}</b><br><small>${v.year} · ${money(v.price)}</small></span><span class="admin-row-actions"><button onclick="editVehicle('${v.id}')">Editar</button><button class="delete" onclick="deleteVehicle('${v.id}')">Eliminar</button></span></div>`).join('')}
window.editVehicle=id=>{let v=vehicles.find(x=>x.id===id);$('#vehicleId').value=v.id;$('#vehicleBrand').value=v.brand;$('#vehicleModel').value=v.model;$('#vehicleYear').value=v.year;$('#vehiclePrice').value=v.price;$('#vehicleCondition').value=v.condition;$('#vehicleType').value=v.type;$('#vehicleKm').value=v.km;$('#vehicleFuel').value=v.fuel;$('#vehicleTransmission').value=v.transmission;$('#vehicleImages').value=v.images.join('\n');$('#vehicleDescription').value=v.description;$('#formTitle').textContent='Editar vehículo';$('#vehicleForm').scrollIntoView({behavior:'smooth'})};
window.deleteVehicle=id=>{if(confirm('¿Eliminar este vehículo?')){vehicles=vehicles.filter(v=>v.id!==id);save()}};
function clearForm(){$('#vehicleForm').reset();$('#vehicleId').value='';$('#formTitle').textContent='Agregar vehículo'}
$('#cancelEdit').onclick=clearForm;
$('#vehicleForm').onsubmit=e=>{e.preventDefault();let current=$('#vehicleId').value;let v={id:current||`${$('#vehicleBrand').value}-${$('#vehicleModel').value}-${Date.now()}`.toLowerCase().replace(/\s+/g,'-'),brand:$('#vehicleBrand').value.trim(),model:$('#vehicleModel').value.trim(),year:+$('#vehicleYear').value,price:+$('#vehiclePrice').value,condition:$('#vehicleCondition').value,type:$('#vehicleType').value,km:+$('#vehicleKm').value,fuel:$('#vehicleFuel').value.trim(),transmission:$('#vehicleTransmission').value.trim(),images:$('#vehicleImages').value.split('\n').map(x=>x.trim()).filter(Boolean),description:$('#vehicleDescription').value.trim()};if(current)vehicles=vehicles.map(x=>x.id===current?v:x);else vehicles.unshift(v);save();clearForm()};
$('#resetCatalog').onclick=()=>{if(confirm('¿Restablecer el catálogo de ejemplo?')){vehicles=structuredClone(defaults);save()}};
$('#exportCatalog').onclick=()=>{let blob=new Blob([JSON.stringify(vehicles,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='catalogo-lrv.json';a.click();URL.revokeObjectURL(a.href)};
render();
